### ISSUE TITLE
100% cpu utilization in a few hours after starting

### ISSUE THREAD

**Issue by pornmailbox** [Cacti/rrdproxy#3]
Hi.
There is some strange behavior of running process:
/usr/bin/php /usr/share/rrdproxy/rrdtool-proxy.php

In a few hours after the container start (after 1-6 hours randomly) rrdtool-proxy.php start utilizing 100% of cpu. If I increase the cpu number, later rrdtool-proxy.php will utilize up to 100% of all cpus continuously.
There is no errors in php_errors.log and dmesg.
Telnet to rrdproxy and switching debug log to "on" indicates no errors. Main cacti continues to work fine, but slowly indicates graphs during this high utilization of rrdproxy resources.

How can I debug the rrdtool-proxy.php and investigate the origin of 100% cpu utilization?
Thank you.

P.S.
I'm using rrdproxy in Proxmox LXC container with gentoo inside, php-7.2.2.
Different php versions is doesn't matter for such behavior of the rrdtool-proxy.php.

**Comment by pornmailbox** [comment]
I've found such an error in php log:
.....PHP Warning:  socket_select(): unable to select [4]: Interrupted system call in /usr/share/rrdproxy/lib/client.php on line 57
.....

This simple patch seems to solve the issue:

[socket_select_simple.patch.txt](https://github.com/Cacti/rrdproxy/files/1907626/socket_select_simple.patch.txt)

Also I updated phpseclib to the latest one [https://github.com/phpseclib/phpseclib/releases/tag/2.0.10](url)

**Comment by browniebraun** [comment]
Can you verify that this patch in combination with the phpseclib upgrade is working faultlessly? I tried to figure out where this loop exists in detail, but haven't found it within client.php. All loops and socket states seem to work faultlessly. And also I had several client processes hanging I was unable to find any hint. Maybe it is somewhere within phpseclib. :/

**Comment by pornmailbox** [comment]
Hi. no I can't. Could help me to enable compete log (for debug) of php? May be this is a php bug. Or may be I need a gdb ? I'm using gcc with lto and graphite optimization.

**Comment by pornmailbox** [comment]
Hi. I made some changes in php.ini and during 4 days it works ok. 
I installed latest phpseclib 2.0.11 also.
If this changes will take affect in next 7-10 days, I'll inform you about my exact changes.

**Comment by netniV** [comment]
Thanks, we will await your next update.

**Comment by pornmailbox** [comment]
Hi. It happened once again. It seems that this is not rrdproxy issue.
I have 2 processes of php with rrdtool-proxy.php with 50% each cpu utilisation, but other 2 processes works fine. Cacti web showing graphs.
I'm using lxc with gentoo (lto+graphite+fastmath gcc otimization, Ofast) with ssl-1.1. 
I need more tests with non-optimized gentoo and alternate centos7 containers for rrdproxy. after maydays I'll report you the results.
Also I try to downgrade to1.x phpseclib.

**Comment by browniebraun** [comment]
I did an upgrade of phpseclib to v2 as well. It does not make any difference. You don't have to downgrade.
Here, I haven't had any zombie processes anymore after disabling the timeout detection.
The proxy allows that a client after its authentication can disable the timeout.
In Cacti modify function __rrd_proxy_init() in /lib/rrd.php at ~line 169:

> 	if ($rrdp_fingerprint != $fingerprint) {
		cacti_log('CACTI2RRDP ERROR: Mismatch RSA Fingerprint.', false, $logopt, POLLER_VERBOSITY_LOW);
		return false;
	} else {
		$rrdproxy = array($rrdp_socket, $rrdp_public_key);
		/* set the rrdtool default font */
		if (read_config_option('path_rrdtool_default_font')) {
			rrdtool_execute("setenv RRD_DEFAULT_FONT '" . read_config_option('path_rrdtool_default_font') . "'", false, RRDTOOL_OUTPUT_NULL, $rrdproxy, $logopt = 'WEBLOG');
		}
		/* disable default timeout */
		rrdtool_execute('setcnn timeout off', false, RRDTOOL_OUTPUT_NULL, $rrdproxy, $logopt = 'WEBLOG');
		return $rrdproxy;
	}

**Comment by pornmailbox** [comment]
Thanks. I'll test it today's night.

**Comment by browniebraun** [comment]
Any results?

**Comment by pornmailbox** [comment]
Hi.
I have 3 lxc containers for my cacti:
1 - cacti with cacti-spine (nginx with php-fpm 7.2.5)
2 - mariadb server
3 - rrdproxy (for storing graphs)
After I made some changes in fpm.conf in cacti container (# 1) (pm.min_spare_servers) I got first cpu 100% utilization (of 6 total) in rrdproxy container (# 3) immediately. This is mean that I have incorrect php-fpm settings in cacti container (# 3). 
This CPU-utilisation bug is not rrdproxy related bug as I investigated today.

**Comment by pornmailbox** [comment]
Hi.
This is not an rrdproxy issue.

I have a Proxmox server with 3 LXC-containers:
1. with cacti (web and cacti-spine poller);
2. mariadb server for cacti;
3. rrdproxy for *.rrd files.

On Proxmox I found in dmesg with every minute interval:
...
... tcp: request_sock_tcp: possible syn flooding on port 40301. sending cookies. check snmp counters.
...
Solution.

Only after I included this lines to proxmox server sysctl.conf :
....
net.ipv4.tcp_syncookies = 1
net.core.somaxconn = 524288
net.ipv4.tcp_max_syn_backlog = 2097152

and listed below lines to sysctl.conf in 'cacti' and 'rrdproxy' LXC-containers:
...
net.ipv4.ip_forward = 1
net.ipv4.tcp_syncookies = 1
net.core.somaxconn = 262144
net.ipv4.tcp_max_syn_backlog = 1048576

my rrdproxy start work normally.
This is a Proxmox and LXC-containers custom specific settings. I think that on a server with own kernel rrdproxy will work normally "from a box".

You can mark "solved" this issue.

P.S.
Such a big values in settings is provisional and can be adopt for a custom requirements.

**Comment by browniebraun** [comment]
I'm happy to see that you were able to fix that. With your agreement I would like to add your recommendations to the README.

**Comment by pornmailbox** [comment]
Hi. Yes, you can. But my mail - "pornamilbox@..." a little bit confuse to be published, especially in README ;-)

**Comment by browniebraun** [comment]
Makes sense.
