### ISSUE TITLE
Misinterpretation of non well-formed transaction strings

### ISSUE THREAD

**Issue by browniebraun** [Cacti/rrdproxy#6]
In Cacti function "rrdtool_function_info" builds following command line string:

`$cmd_line = ' info ' . $data_source_path;`

RRDproxy uses a blank to split the RRDtool command as well as parameters  that may follow. The leading blank in front will be misinterpreted as a request to get the RRDtool's general info page.
This ends up in an invalid command like "info info ./123/456678.rrd" being written to the RRDtool server pipe.

**Comment by netniV** [comment]
Interesting catch

**Comment by browniebraun** [comment]
yep, noticed that behaviour in debug mode while I was trying to figure out why the DS info in Cacti does not work.
